// src/app/(dashboard)/organizer/layout.tsx
// This remains a Server Component
import DashboardClientWrapper from "@/components/DashboardClientWrapper";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Initialize fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Server component can export metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Server component layout
export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* Client component wrapper handles all client-side functionality */}
      <DashboardClientWrapper>{children}</DashboardClientWrapper>
    </div>
  );
}
